/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>

#include <string.h>
#include "com_lll_common_encryption_EncryptionUtils.h"

using namespace std;

/* Header for class com_lll_common_encryption_EncryptionUtils */

/*
 * Class:     com_lll_common_encryption_EncryptionUtils
 * Method:    getSign
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lll_common_encryption_EncryptionUtils_getSign
        (JNIEnv *env, jclass jcla, jstring jstr) {

    return env->NewStringUTF("HelloFrom JNI!");
}


/*
 * Class:     com_lll_common_encryption_EncryptionUtils
 * Method:    encryptionString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lll_common_encryption_EncryptionUtils_encryptionString__Ljava_lang_String_2
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_lll_common_encryption_EncryptionUtils
 * Method:    encryptionString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lll_common_encryption_EncryptionUtils_encryptionString__Ljava_lang_String_2Ljava_lang_String_2
        (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_lll_common_encryption_EncryptionUtils
 * Method:    decryptionString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lll_common_encryption_EncryptionUtils_decryptionString__Ljava_lang_String_2
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_lll_common_encryption_EncryptionUtils
 * Method:    decryptionString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lll_common_encryption_EncryptionUtils_decryptionString__Ljava_lang_String_2Ljava_lang_String_2
        (JNIEnv *, jclass, jstring, jstring) {

}

/**
 将Java string 转为c 字符串
*/
char *jStr2CStr(JNIEnv *env, jclass jcla, jstring jstr) {


}

